#!/usr/bin/env bash
# ================================================================
#  setup.sh  -  InsiderJobs Local Development Setup
#
#  Run this ONCE after cloning the repository.
#  It will:
#    1. Check system requirements (Node, npm, Git)
#    2. Prompt you for all required secret values
#    3. Create server/.env and client/.env automatically
#    4. Install npm dependencies for both server and client
#
#  Usage (Git Bash / WSL):
#    chmod +x setup.sh start-local.sh   (first time only)
#    ./setup.sh
#
#  After setup, start the app with:
#    ./start-local.sh
# ================================================================

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_ENV="$ROOT_DIR/server/.env"
CLIENT_ENV="$ROOT_DIR/client/.env"

# ── Helpers ───────────────────────────────────────────────────
ok()   { echo -e "  ${GREEN}+${RESET}  $*"; }
warn() { echo -e "  ${YELLOW}!${RESET}  $*"; }
info() { echo -e "  ${CYAN}>${RESET}  $*"; }
err()  { echo -e "  ${RED}x${RESET}  $*" >&2; }
step() { echo -e "\n${BOLD}${CYAN}==  $*${RESET}"; }

# Ask for a required value — re-prompts if left blank
# Usage: ask_required "DISPLAY_NAME" "ENV_KEY"  -> echoes value
ask_required() {
  local label="$1"
  local key="$2"
  local value=""
  while [ -z "$value" ]; do
    printf "  Enter %-30s : " "$key"
    read -r value
    if [ -z "$value" ]; then
      echo -e "  ${YELLOW}!${RESET}  $key cannot be empty. Please enter a value."
    fi
  done
  echo "$value"
}

# ── Banner ────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}================================================================${RESET}"
echo -e "${CYAN}${BOLD}   InsiderJobs  -  Local Development Setup                     ${RESET}"
echo -e "${CYAN}${BOLD}================================================================${RESET}"
echo ""

# ── Step 1: System requirements ──────────────────────────────
step "Step 1/4 : Checking system requirements"

for cmd in node npm git; do
  if command -v "$cmd" &>/dev/null; then
    ok "$cmd   $(command -v $cmd)"
  else
    err "$cmd is NOT installed. Install it and re-run setup."
    exit 1
  fi
done
ok "Node $(node --version)   npm v$(npm --version)"

# ── Step 2: Guard existing .env files ────────────────────────
step "Step 2/4 : Configuring environment variables"

SKIP_SERVER=false
SKIP_CLIENT=false

if [ -f "$SERVER_ENV" ]; then
  warn "server/.env already exists."
  printf "  Overwrite it? (y/N) : "
  read -r ow_server
  [[ "$ow_server" =~ ^[Yy]$ ]] || SKIP_SERVER=true
fi

if [ -f "$CLIENT_ENV" ]; then
  warn "client/.env already exists."
  printf "  Overwrite it? (y/N) : "
  read -r ow_client
  [[ "$ow_client" =~ ^[Yy]$ ]] || SKIP_CLIENT=true
fi

# ── Server .env ───────────────────────────────────────────────
if [ "$SKIP_SERVER" = false ]; then
  echo ""
  echo -e "  ${DIM}--- Server credentials (all fields required) ---${RESET}"
  echo ""

  MONGODB_URI=$(ask_required   "MongoDB Atlas URI"       "MONGODB_URI")
  JWT_SECRET=$(ask_required    "JWT secret string"       "JWT_SECRET")
  CLOUDINARY_NAME=$(ask_required   "Cloudinary cloud name"   "CLOUDINARY_NAME")
  CLOUDINARY_API_KEY=$(ask_required "Cloudinary API key"     "CLOUDINARY_API_KEY")
  CLOUDINARY_API_SECRET=$(ask_required "Cloudinary API secret" "CLOUDINARY_API_SECRET")
  GEMINI_API_KEY=$(ask_required "Gemini API key"           "GEMINI_API_KEY")
  SMTP_USER=$(ask_required     "Gmail address (SMTP)"    "SMTP_USER")
  SMTP_PASS=$(ask_required     "Gmail app password"      "SMTP_PASS")

  cat > "$SERVER_ENV" <<EOF
# Auto-generated by setup.sh
# Edit this file directly to change any value.

PORT=5000
PROJECT_NAME="Insider Jobs"
JWT_SECRET="$JWT_SECRET"

MONGODB_URI=$MONGODB_URI

CLOUDINARY_NAME="$CLOUDINARY_NAME"
CLOUDINARY_API_KEY="$CLOUDINARY_API_KEY"
CLOUDINARY_API_SECRET="$CLOUDINARY_API_SECRET"

GEMINI_API_KEY="$GEMINI_API_KEY"
GEMINI_BASE_URL="https://generativelanguage.googleapis.com/v1beta/openai/"
GEMINI_MODEL="gemini-2.5-flash"

SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=$SMTP_USER
SMTP_PASS=$SMTP_PASS
EOF

  ok "server/.env created."
else
  info "Skipped server/.env — existing file kept."
fi

# ── Client .env ───────────────────────────────────────────────
if [ "$SKIP_CLIENT" = false ]; then
  echo ""
  echo -e "  ${DIM}--- Client / Frontend (press Enter for local default) ---${RESET}"
  echo ""

  printf "  Enter VITE_REACT_BACKEND_URL [http://localhost:5000] : "
  read -r VITE_BACKEND
  [ -z "$VITE_BACKEND" ] && VITE_BACKEND="http://localhost:5000"

  cat > "$CLIENT_ENV" <<EOF
# Auto-generated by setup.sh
VITE_REACT_BACKEND_URL=$VITE_BACKEND
EOF

  ok "client/.env created."
else
  info "Skipped client/.env — existing file kept."
fi

# ── Step 3: Install dependencies ─────────────────────────────
step "Step 3/4 : Installing npm dependencies"

echo ""
info "Installing server packages..."
npm install --prefix "$ROOT_DIR/server" --silent
ok "server/node_modules ready."

echo ""
info "Installing client packages..."
npm install --prefix "$ROOT_DIR/client" --silent
ok "client/node_modules ready."

# ── Step 4: Verify ────────────────────────────────────────────
step "Step 4/4 : Verifying setup"

for f in "$SERVER_ENV" "$CLIENT_ENV"; do
  label="${f#$ROOT_DIR/}"
  if [ -f "$f" ]; then
    ok "$label  ($(wc -l < "$f") lines)"
  else
    err "$label was NOT created — check for errors above."
    exit 1
  fi
done

# ── Done ──────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}================================================================${RESET}"
echo -e "${GREEN}${BOLD}   Setup complete! You are ready to go.                        ${RESET}"
echo -e "${GREEN}${BOLD}================================================================${RESET}"
echo ""
echo -e "  Run the app:"
echo -e "    ${CYAN}./start-local.sh${RESET}"
echo ""
echo -e "  Backend  ->  http://localhost:5000"
echo -e "  Frontend ->  http://localhost:5173"
echo ""
echo -e "  ${DIM}To change env values later, edit:${RESET}"
echo -e "  ${DIM}  server/.env   |   client/.env${RESET}"
echo ""
