#!/bin/bash
set -euo pipefail

# Resolve the project root regardless of where the script is called from
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$ROOT_DIR/server"
CLIENT_DIR="$ROOT_DIR/client"

echo "================================="
echo " InsiderJobs  -  Local Dev Setup "
echo "================================="

# ── Verify project directories ────────────────────────────────
if [ ! -d "$SERVER_DIR" ]; then
    echo "Error: server directory not found at $SERVER_DIR!"
    exit 1
fi

if [ ! -d "$CLIENT_DIR" ]; then
    echo "Error: client directory not found at $CLIENT_DIR!"
    exit 1
fi

# ── Check required tools ──────────────────────────────────────
echo ""
echo "Checking system requirements..."

for cmd in node npm git; do
    if command -v "$cmd" &>/dev/null; then
        echo "  OK  $cmd $(command -v $cmd)"
    else
        echo "  ERROR  $cmd is not installed. Please install it and re-run setup."
        exit 1
    fi
done

echo ""

# ── Guard: existing .env files ───────────────────────────────
SKIP_SERVER=false
SKIP_CLIENT=false

if [ -f "$SERVER_DIR/.env" ]; then
    echo "Warning: server/.env already exists."
    read -rp "  Overwrite it? (y/N): " ow_server
    [[ "$ow_server" =~ ^[Yy]$ ]] || SKIP_SERVER=true
fi

if [ -f "$CLIENT_DIR/.env" ]; then
    echo "Warning: client/.env already exists."
    read -rp "  Overwrite it? (y/N): " ow_client
    [[ "$ow_client" =~ ^[Yy]$ ]] || SKIP_CLIENT=true
fi

# ── Server .env ───────────────────────────────────────────────
if [ "$SKIP_SERVER" = false ]; then
    echo ""
    echo "--- Configure server/.env ---"
    echo ""

    read -rp "Enter PROJECT_NAME: " PROJECT_NAME
    while [ -z "$PROJECT_NAME" ]; do
        echo "  PROJECT_NAME cannot be empty."
        read -rp "Enter PROJECT_NAME: " PROJECT_NAME
    done

    read -rp "Enter MONGODB_URI: " MONGODB_URI
    while [ -z "$MONGODB_URI" ]; do
        echo "  MONGODB_URI cannot be empty."
        read -rp "Enter MONGODB_URI: " MONGODB_URI
    done

    read -rp "Enter CLOUDINARY_NAME: " CLOUDINARY_NAME
    while [ -z "$CLOUDINARY_NAME" ]; do
        echo "  CLOUDINARY_NAME cannot be empty."
        read -rp "Enter CLOUDINARY_NAME: " CLOUDINARY_NAME
    done

    read -rp "Enter CLOUDINARY_API_KEY: " CLOUDINARY_API_KEY
    while [ -z "$CLOUDINARY_API_KEY" ]; do
        echo "  CLOUDINARY_API_KEY cannot be empty."
        read -rp "Enter CLOUDINARY_API_KEY: " CLOUDINARY_API_KEY
    done

    read -rp "Enter CLOUDINARY_API_SECRET: " CLOUDINARY_API_SECRET
    while [ -z "$CLOUDINARY_API_SECRET" ]; do
        echo "  CLOUDINARY_API_SECRET cannot be empty."
        read -rp "Enter CLOUDINARY_API_SECRET: " CLOUDINARY_API_SECRET
    done

    read -rp "Enter GEMINI_API_KEY: " GEMINI_API_KEY
    while [ -z "$GEMINI_API_KEY" ]; do
        echo "  GEMINI_API_KEY cannot be empty."
        read -rp "Enter GEMINI_API_KEY: " GEMINI_API_KEY
    done

    read -rp "Enter SMTP_USER (Gmail address): " SMTP_USER
    while [ -z "$SMTP_USER" ]; do
        echo "  SMTP_USER cannot be empty."
        read -rp "Enter SMTP_USER (Gmail address): " SMTP_USER
    done

    read -rp "Enter SMTP_PASS (Gmail app password): " SMTP_PASS
    while [ -z "$SMTP_PASS" ]; do
        echo "  SMTP_PASS cannot be empty."
        read -rp "Enter SMTP_PASS (Gmail app password): " SMTP_PASS
    done

    # Auto-generate a cryptographically secure JWT secret
    if command -v node &>/dev/null; then
        JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(64).toString('hex'))")
    elif command -v openssl &>/dev/null; then
        JWT_SECRET=$(openssl rand -hex 64)
    else
        echo "Warning: Could not auto-generate JWT_SECRET. Using a timestamp-based fallback."
        JWT_SECRET="CHANGE_ME_$(date +%s)"
    fi

    echo ""
    echo "OK  Generated a cryptographically secure JWT_SECRET automatically."

    cat > "$SERVER_DIR/.env" << EOF
# Auto-generated by setup.sh
# Edit this file directly to change any value.

PORT=5000
PROJECT_NAME=$PROJECT_NAME
JWT_SECRET=$JWT_SECRET

MONGODB_URI=$MONGODB_URI

CLOUDINARY_NAME=$CLOUDINARY_NAME
CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET

GEMINI_API_KEY=$GEMINI_API_KEY
GEMINI_BASE_URL="https://generativelanguage.googleapis.com/v1beta/openai/"
GEMINI_MODEL="gemini-2.5-flash"

SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=$SMTP_USER
SMTP_PASS=$SMTP_PASS
EOF

    echo "OK  server/.env created."
else
    echo "Skipped server/.env — existing file kept."
fi

# ── Client .env ───────────────────────────────────────────────
if [ "$SKIP_CLIENT" = false ]; then
    echo ""
    echo "--- Configure client/.env ---"
    echo ""

    read -rp "Enter VITE_REACT_BACKEND_URL [http://localhost:5000]: " VITE_BACKEND
    [ -z "$VITE_BACKEND" ] && VITE_BACKEND="http://localhost:5000"

    cat > "$CLIENT_DIR/.env" << EOF
# Auto-generated by setup.sh
VITE_REACT_BACKEND_URL=$VITE_BACKEND
EOF

    echo "OK  client/.env created."
else
    echo "Skipped client/.env — existing file kept."
fi

# ── Install dependencies ──────────────────────────────────────
echo ""
echo "--- Installing dependencies ---"
echo ""

echo "Installing server packages..."
(
    cd "$SERVER_DIR"
    npm install
)
echo "OK server packages installed."

echo "Installing client packages..."
(
    cd "$CLIENT_DIR"
    npm install
)
echo "OK client packages installed."

# ── Done ──────────────────────────────────────────────────────
echo ""
echo "OK  Environment files created successfully!"
echo "   server/.env  ->  PORT, JWT_SECRET (auto), MONGODB_URI, CLOUDINARY_*, GEMINI_*, SMTP_*"
echo "   client/.env  ->  VITE_REACT_BACKEND_URL"
echo ""
echo "Next steps:"
echo "  ./start-local.sh"
echo ""
echo "  Backend  ->  http://localhost:5000"
echo "  Frontend ->  http://localhost:5173"
echo ""
echo "Setup complete!"
